// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://yggvabrltcxvkiyjixdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZ3ZhYnJsdGN4dmtpeWppeGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMTI5MzcsImV4cCI6MjA3ODU4ODkzN30.fU1VYjYGRxDwADO6RoYvb1CxIfJUnkEL386aEAPgRqQ";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

// Ensure URL doesn't have trailing slash
const cleanUrl = SUPABASE_URL.replace(/\/$/, '');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(cleanUrl, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});